### ISSUE TITLE
Error w/ AWS Lambda Handler

### ISSUE THREAD

**Issue by atwoodjw** [kevva/get-proxy#4]
I'm trying to use [download](https://github.com/kevva/download) within an AWS Lambda Handler, written in Node.js, but I'm seeing an error.

```
{
  "errorMessage": "rc(name): name *must* be string",
  "errorType": "Error",
  ...
}
```

The following line seems to be the culprit.

```
const conf = require('rc')('npm');
```

**Comment by kevva** [comment]
That's weird. We clearly define a name (`npm`).

**Comment by atwoodjw** [comment]
Here's a [Gist](https://gist.github.com/atwoodjw/dab5507b65785f6ee19700c9306ab080) for the handler.

The code is simple, but I'm running through Browserify.

```
function handler(event, context, cb) {

  var conf = require('rc')('npm');

  return cb(null, {
    message: 'Your Lambda function executed successfully!'
  });
}

exports.handler = handler;
```

**Comment by SamVerschueren** [comment]
I might not be following here but why are you using browserify for AWS Lambda? Lambda isn't a browser, it's just a service that executes your node app within a docker container.

Just write your code, zip everything and upload to lambda.

**Comment by atwoodjw** [comment]
I'm using the [Serverless](https://github.com/serverless/serverless) framework with the [Optimizer](https://github.com/serverless/serverless-optimizer-plugin) plugin. This isn't required, but reduces the file sizes of functions and purportedly decreases provisioning time.

I can setup an example function that doesn't use the Optimizer plugin if that's helpful.

**Comment by SamVerschueren** [comment]
Try it without the optimizer plugin first to make sure it's not a browserify issue.

**Comment by atwoodjw** [comment]
Browserify does not support !module.parent, which `rc` uses for a conditional log statement.

Please close.
